# Generated by Django 5.2.17 on 2026-08-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wx_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="welcome",
            options={"verbose_name_plural": "欢迎表"},
        ),
    ]
